crashlogd: fix compilation error, undefined MIN/MAX
Building crashlogd causes an ICE (internal compilation error)
because the macros MIN and MAX are not defined.

This issue was reported on Sofia3G, Android 4.4.

Change-Id: I7d1ca05f6f3d64b44572540f3e5090facc9827e6
Tracked-On: https://jira01.devtools.intel.com/browse/IMINAN-8069
Signed-off-by: Olivier Fourdan <olivier.fourdan@intel.com>
Reviewed-on: https://android.intel.com:443/297302