crashlogd: fix compilation error on Sofia
BZ: 226593

Building crashlogd causes an ICE (internal compilation error)
because the macros MIN and MAX are not defined.

Change-Id: I7d1ca05f6f3d64b44572540f3e5090facc9827e6
Signed-off-by: Olivier Fourdan <olivier.fourdan@intel.com>
Reviewed-on: https://android.intel.com:443/288671